%Function written by Adam Li on 07/28/14
%Input: - dirName is the directory name location
%       - expName is the experiment name (e.g. walk, sitstand, turn,etc.)
%       with 001/101 and c1/c2
%       So it would look like 'SitStand_001_c1'
%
%Output: - vidOutput is a video file with all the 
%images inputted into the file one by one
%Description: Saves all the skeletal data into a stream of images
%and saves it as a video

function reanimateSkeleton(mainDir, fileName)
    workingDir = mainDir;              %carries us into Camera_date folder
    
    %read data and import columns as column vectors
    [head_x	 head_y	 head_z...
        shoulder_center_x	 shoulder_center_y	 shoulder_center_z...
        spine_x	 spine_y	 spine_z...
        hip_center_x	 hip_center_y	 hip_center_z...
        shoulder_left_x	 shoulder_left_y	 shoulder_left_z...
        elbow_left_x	 elbow_left_y	 elbow_left_z...
        wrist_left_x	 wrist_left_y	 wrist_left_z...
        hand_left_x	 hand_left_y hand_left_z...
        shoulder_right_x shoulder_right_y shoulder_right_z...
        elbow_right_x	 elbow_right_y	 elbow_right_z...
        wrist_right_x	 wrist_right_y	 wrist_right_z...
        hand_right_x	 hand_right_y	 hand_right_z...
        hip_left_x	 hip_left_y	 hip_left_z...
        knee_left_x  knee_left_y	 knee_left_z...
        ankle_left_x	 ankle_left_y	 ankle_left_z...
        foot_left_x	 foot_left_y	 foot_left_z...
        hip_right_x	 hip_right_y	 hip_right_z...
        knee_right_x	 knee_right_y	 knee_right_z...
        ankle_right_x	 ankle_right_y   ankle_right_z...
        foot_right_x	 foot_right_y	 foot_right_z] = csvimport(fileName, ...
        'columns', {'head_x',	'head_y',  'head_z',...
        'shoulder_center_x', 'shoulder_center_y', 'shoulder_center_z',...
        'spine_x', 'spine_y', 'spine_z',...
        'hip center_x', 'hip center_y', 'hip center_z',...
        'shoulder left_x', 'shoulder left_y', 'shoulder left_z',...
        'elbow left_x',	'elbow left_y',	 'elbow left_z',...
        'wrist left_x',	 'wrist left_y', 'wrist left_z',...
        'hand left_x',	 'hand left_y',	 'hand left_z',...
        'shoulder right_x',	 'shoulder right_y', 'shoulder right_z',...
        'elbow right_x', 'elbow right_y',	'elbow right_z',...
        'wrist right_x', 'wrist right_y', 'wrist right_z',...
        'hand right_x',	 'hand right_y', 'hand right_z',...
        'hip left_x',	 'hip left_y', 'hip left_z',...
        'knee left_x',  'knee left_y', 'knee left_z',...
        'ankle left_x',	 'ankle left_y', 'ankle left_z',...
        'foot left_x',	 'foot left_y', 'foot left_z',...
        'hip right_x',	 'hip right_y', 'hip right_z',...
        'knee right_x',	 'knee right_y', 'knee right_z',...
        'ankle right_x', 'ankle right_y', 'ankle right_z',...
        'foot right_x',	 'foot right_y', 'foot right_z'});

    
        
end