%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/adam2392/Documents/MATLAB/Neural_Interaction_Lab_MatlabForPD/01_Setup/Skeleton_Walk_022.1_c2_18.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

%ONLY USE IF NEEDED
% e.g. importSkeleton_Helper('/Users/adam2392/Desktop/Analysis
% Folder/022.1/Skeleton_Walk_022.1_c2_18.csv')

% Auto-generated by MATLAB on 2015/04/11 22:20:50


function [head_x, head_y, head_z,...
                shoulder_center_x, shoulder_center_y, shoulder_center_z,...
                spine_x,	 spine_y,	 spine_z,...
                hip_center_x,	 hip_center_y,	 hip_center_z,...
                shoulder_left_x,	 shoulder_left_y,	 shoulder_left_z,...
                elbow_left_x,	 elbow_left_y,	 elbow_left_z,...
                wrist_left_x,	 wrist_left_y,	 wrist_left_z,...
                hand_left_x,	 hand_left_y, hand_left_z,...
                shoulder_right_x, shoulder_right_y, shoulder_right_z,...
                elbow_right_x,	 elbow_right_y,	 elbow_right_z,...
                wrist_right_x,	 wrist_right_y,	 wrist_right_z,...
                hand_right_x,	 hand_right_y,	 hand_right_z,...
                hip_left_x,	 hip_left_y,	 hip_left_z,...
                knee_left_x,  knee_left_y,	 knee_left_z,...
                ankle_left_x,	 ankle_left_y,	 ankle_left_z,...
                foot_left_x,	 foot_left_y,	 foot_left_z,...
                hip_right_x,	 hip_right_y,	 hip_right_z,...
                knee_right_x,	 knee_right_y,	 knee_right_z,...
                ankle_right_x,	 ankle_right_y,   ankle_right_z,...
                foot_right_x,	 foot_right_y,	 foot_right_z,...
                time_stamp] = importSkeleton_Helper(csvFiles)

    %% Initialize variables.
    filename = csvFiles;
    delimiter = ',';
    startRow = 2;

    %% Format string for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: double (%f)
    %	column4: double (%f)
    %   column5: double (%f)
    %	column6: double (%f)
    %   column7: double (%f)
    %	column8: double (%f)
    %   column9: double (%f)
    %	column10: double (%f)
    %   column11: double (%f)
    %	column12: double (%f)
    %   column13: double (%f)
    %	column14: double (%f)
    %   column15: double (%f)
    %	column16: double (%f)
    %   column17: double (%f)
    %	column18: double (%f)
    %   column19: double (%f)
    %	column20: double (%f)
    %   column21: double (%f)
    %	column22: double (%f)
    %   column23: double (%f)
    %	column24: double (%f)
    %   column25: double (%f)
    %	column26: double (%f)
    %   column27: double (%f)
    %	column28: double (%f)
    %   column29: double (%f)
    %	column30: double (%f)
    %   column31: double (%f)
    %	column32: double (%f)
    %   column33: double (%f)
    %	column34: double (%f)
    %   column35: double (%f)
    %	column36: double (%f)
    %   column37: double (%f)
    %	column38: double (%f)
    %   column39: double (%f)
    %	column40: double (%f)
    %   column41: double (%f)
    %	column42: double (%f)
    %   column43: double (%f)
    %	column44: double (%f)
    %   column45: double (%f)
    %	column46: double (%f)
    %   column47: double (%f)
    %	column48: double (%f)
    %   column49: double (%f)
    %	column50: double (%f)
    %   column51: double (%f)
    %	column52: double (%f)
    %   column53: double (%f)
    %	column54: double (%f)
    %   column55: double (%f)
    %	column56: double (%f)
    %   column57: double (%f)
    %	column58: double (%f)
    %   column59: double (%f)
    %	column60: double (%f)
    %   column61: text (%s)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%[^\n\r]';

    %% Open the text file.
    fileID = fopen(filename,'r');

    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this
    % code. If an error occurs for a different file, try regenerating the code
    % from the Import Tool.
    dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

    %% Close the text file.
    fclose(fileID);

    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for
    % unimportable data, select unimportable cells in a file and regenerate the
    % script.

    %% Allocate imported array to column variable names
    head_x = dataArray{:, 1};
    head_y = dataArray{:, 2};
    head_z = dataArray{:, 3};
    shoulder_center_x = dataArray{:, 4};
    shoulder_center_y = dataArray{:, 5};
    shoulder_center_z = dataArray{:, 6};
    spine_x = dataArray{:, 7};
    spine_y = dataArray{:, 8};
    spine_z = dataArray{:, 9};
    hip_center_x = dataArray{:, 10};
    hip_center_y = dataArray{:, 11};
    hip_center_z = dataArray{:, 12};
    shoulder_left_x = dataArray{:, 13};
    shoulder_left_y = dataArray{:, 14};
    shoulder_left_z = dataArray{:, 15};
    elbow_left_x = dataArray{:, 16};
    elbow_left_y = dataArray{:, 17};
    elbow_left_z = dataArray{:, 18};
    wrist_left_x = dataArray{:, 19};
    wrist_left_y = dataArray{:, 20};
    wrist_left_z = dataArray{:, 21};
    hand_left_x = dataArray{:, 22};
    hand_left_y = dataArray{:, 23};
    hand_left_z = dataArray{:, 24};
    shoulder_right_x = dataArray{:, 25};
    shoulder_right_y = dataArray{:, 26};
    shoulder_right_z = dataArray{:, 27};
    elbow_right_x = dataArray{:, 28};
    elbow_right_y = dataArray{:, 29};
    elbow_right_z = dataArray{:, 30};
    wrist_right_x = dataArray{:, 31};
    wrist_right_y = dataArray{:, 32};
    wrist_right_z = dataArray{:, 33};
    hand_right_x = dataArray{:, 34};
    hand_right_y = dataArray{:, 35};
    hand_right_z = dataArray{:, 36};
    hip_left_x = dataArray{:, 37};
    hip_left_y = dataArray{:, 38};
    hip_left_z = dataArray{:, 39};
    knee_left_x = dataArray{:, 40};
    knee_left_y = dataArray{:, 41};
    knee_left_z = dataArray{:, 42};
    ankle_left_x = dataArray{:, 43};
    ankle_left_y = dataArray{:, 44};
    ankle_left_z = dataArray{:, 45};
    foot_left_x = dataArray{:, 46};
    foot_left_y = dataArray{:, 47};
    foot_left_z = dataArray{:, 48};
    hip_right_x = dataArray{:, 49};
    hip_right_y = dataArray{:, 50};
    hip_right_z = dataArray{:, 51};
    knee_right_x = dataArray{:, 52};
    knee_right_y = dataArray{:, 53};
    knee_right_z = dataArray{:, 54};
    ankle_right_x = dataArray{:, 55};
    ankle_right_y = dataArray{:, 56};
    ankle_right_z = dataArray{:, 57};
    foot_right_x = dataArray{:, 58};
    foot_right_y = dataArray{:, 59};
    foot_right_z = dataArray{:, 60};
    time_stamp = dataArray{:, 61};


    %% Clear temporary variables
    clearvars filename delimiter startRow formatSpec fileID dataArray ans;
end