%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/adam2392/Documents/MATLAB/Neural_Interaction_Lab_MatlabForPD/05_Eparc/David_Walk_Compiled_121.xlsx

% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/09/18 22:15:32

%% Import the data
patient = '121';
[~, ~, raw] = xlsread(strcat('/Users/adam2392/Documents/MATLAB/Neural_Interaction_Lab_MatlabForPD/05_Eparc/David_Walk_Compiled_', patient,'.xlsx'),'Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
SubjectName = data(:,1);
Trial = data(:,2);
StepWidthcm = data(:,3);
StepLengthcm = data(:,4);
Speedcms = data(:,5);
StepLengthSymmetry = data(:,6);
Height = data(:,7);
DateofBirth = data(:,8);
TestTime = data(:,9);
TestDate = data(:,10);

%% Clear temporary variables
clearvars data raw R;